# Generated by Django 5.2.8 on 2025-12-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='questionnaires.question')),
            ],
        ),
    ]
