# Generated by Django 5.2.8 on 2025-12-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_questiondependency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questiondependency',
            name='option',
        ),
        migrations.RemoveField(
            model_name='questiondependency',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='questiondependency',
            name='question',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_answer',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionDependency',
        ),
    ]
